nix-community/srvos

profiles/server.nix

As far as I can see only desktop environments are enabling this option. This is a rather low-level service, which seems unlikely to get enabled by accident.
However setting this option to false will break `xrdp` in combination with a desktop environment usage which is something you may need every once in a while even in a server context.

drop udisks2 from server profile

---

profiles/server.nix

This is default on GCP for example and in Google’s internal backbone networks and google.com and YouTube Web servers throughput increased by 4 percent on average globally – and by more than 14 percent in some countries.

server: set tcp BBR as default congestion control

---

common/well-known-hosts.nix

This gets rid of the dummy hostnames of `github-rsa`, `github-ed25519`, etc from the `/etc/ssh/ssh_known_hosts` file.

well-known-hosts: define hostNames instead of extraHostNames

---

README.md
default.nix
flake.nix
mixins/trusted-nix-caches.nix

This adds a list of common trust-worthy caches. It's not enabled by default since it's debatable what caches should be enabled by default.

add trusted caches mixins

---

mixins/nginx.nix

The option was removed in cb73862665c040d89fbb4a66210ead376f69e468

mixins-nginx: remove validateConfig

---

nixos/common/nix.nix

This fixes the problem, that you cannot add to more experimental features in another config

fix: make experimental-features a list

---

flake.lock
nixos/common/default.nix

this is now upstream: https://github.com/NixOS/nixpkgs/pull/214153

common: drop Nsncd option

---

nixos/roles/github-actions-runner.nix

Some workflows assume packages to be installed by default (e.g. bld). Sometime helpful to not run devshell in all workflows.

feat(github-runners): add option to install default packages

---

flake.lock
flake.nix

otherwise we end up with a second 30mb nixpkgs.
bors merge

explicitly add flake-parts with override

---

docs/design.md
nixos/common/default.nix
nixos/desktop/default.nix
nixos/hardware/amazon/default.nix
nixos/hardware/hetzner-cloud/default.nix
nixos/hardware/hetzner-online/amd.nix
nixos/hardware/hetzner-online/intel.nix
nixos/mixins/cloud-init.nix
nixos/mixins/nginx.nix
nixos/mixins/systemd-boot.nix
nixos/mixins/telegraf.nix
nixos/mixins/terminfo.nix
nixos/mixins/tracing.nix
nixos/roles/github-actions-runner.nix
nixos/roles/nix-remote-builder.nix
nixos/server/default.nix

After #80, the modules are exposed as paths, and Nix doesn't seem to
complain anymore.
This is probably a change in Nix itself. But that means we don't need
those `_file` anymore.

remove the _file references

---

nixos/roles/github-actions-runner.nix

the systemd option is invalid and the device should be world-readable.

github-actions-runner: drop kvm extra group

---

nixos/modules/github-runners/remove_existing_runner.sh
nixos/modules/github-runners/service.nix
nixos/modules/github-runners/token.sh

The GitHub self-hosted runner service can unregister existing GitHub runners if their token still exists in the runner's state directory. However, if the runner is still registered and the token no longer exists, the service is unable to unregister the runner, and it cannot be started again as it is already registered.
Rather than relying on the token stored in the runner's state directory, this change enables the service to unregister an existing offline runner using the GitHub App token.

fix(github-runner): unregister existing offline runner using GitHub App token

---

nixos/common/well-known-hosts.nix

GitHub changed their RSA pubkey on March 23. <https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/>

well-known-hosts: update rsa pubkey for GitHub

---

nixos/roles/github-actions-runner.nix

Introduces the `extraLabels` option to the GitHub action runners role, enabling users to target specific runners using custom labels.

feat(github-runner): add role option to add extra labels

---

nixos/common/well-known-hosts.nix

well-known-hosts: remove RSA keys

---

bors.toml
nixos/roles/github-actions-runner.nix
nixos/test-configurations.nix

Add option to enable asynchronous process to upload Nix packages to a binary cache without requiring the use of Cachix. Based on https://github.com/nix-community/queued-build-hook

feat(github-runner): add optional async post build hook

---

nixos/hardware/hetzner-cloud/default.nix

Thanks to @jfroche fixing cloud-init in
https://github.com/NixOS/nixpkgs/pull/226216, it's now able to retrieve
the IPv6 address from the metadata server on boot and creates a
/etc/systemd/network/10-cloud-init-eth0.network file that contains it.

hetzner-cloud: detect IPv6 automatically

---

nixos/mixins/telegraf.nix

It makes telegraf otherwise errors if /proc/mdstat is not available.

telegraf: make mdstat monitoring option

---

nixos/common/flake.nix
nixos/common/upgrade-diff.nix

This is something I found useful while testing in preparation to roll out srvos to a few of my machines. Should be safe as the `nix store diff-closures` doesn't do writes and is pretty quick.
The delimiters around it makes it easier to parse IMO, but I am happy to remove them :)

Allow upgrade-diff to run during dry-activate

---

nixos/common/networking.nix

Hello! 
I think not logging each and every refused connection is a good default, as running a public server quickly leads to unreadable dmesg output, due to scanning et al.

common: don't log refused network connections

---

nixos/common/default.nix
nixos/hardware/hetzner-cloud/default.nix

Hello! Just noticed that `boot.tmp.cleanOnBoot` is only enabled on hetzner-cloud machines in srvos. Is there any drawback in doing so on all machines by default or shall we change that? :)

common: default to boot.tmp.cleanOnBoot=true

---

nixos/common/openssh.nix

Harden the OpenSSH server. This change reduces the compatibility to OpenSSH 6.5 and later.
PortZero's security review inspired this change.

openssh: use recommended key exchange algorithms

---

nixos/common/nix.nix

Nixpkgs distributed nix 2.15 which breaks on nix-copy-closure.

common: pin to nix to v2.16 for now

---

nixos/modules/github-runners/options.nix
nixos/modules/github-runners/service.nix
nixos/roles/github-actions-runner.nix

As many actions don't yet support Node 20 it is useful to be able to specify which versions should be available. This PR makes that possible by incorporating the changes found [here](https://github.com/NixOS/nixpkgs/pull/249103/commits/388bfcef4a51efb55b2b447d2634d16ce486d32c).
At the time of writing the CI is failing because Node 16 is required.

feat(github-runners): add 'nodeRuntimes' option

---

nixos/mixins/telegraf.nix

Useful to see drops/errors/timeouts from the agent.

telegraf: add internal

---

nixos/common/nix.nix

Impure-derivations and auto-allocate-uids seem to be pretty stable and are not used if not requested by a build. repl-flake changes the behaviour of nix repl, but this change will be considered stable in the next release anyway.

nix-daemon: enable more experimental features

---

nixos/hardware/hetzner-online/default.nix

...and match probable names of the first interface according to
https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
matchConfig.Name is a whitespace-separated list of shell-style globs according to man 5 systemd.network.
old-style eth0 is kept to ease switching between interface naming schemes and because it seems harmless to do so.

hetzner-online: use predictable interface names

---

nixos/roles/github-actions-runner.nix

To keep backward compatibility, the GitHub runner role is not enabled by an `enabled` option but is enabled when the `url` option is defined.

Allow GitHub runner role to be included in nixosModules.default

---

.github/workflows/update-dev-flake-lock.yml

Currently both actions have the same name.

.github/workflows/update-dev-flake-lock.yml: update name

---

nixos/common/default.nix

Whether the sudo lecture is shown is stateful. On nixos systems that don't store state you will see the sudo lecture a lot, so I find it useful to disable it

Disable sudo lecture

---

nixos/common/default.nix
nixos/common/sudo.nix

Was found in https://xeiaso.net/blog/paranoid-nixos-2021-07-18/
I'm also moving things out of the default.nix, so they can more easily be cherry-picked.

sudo: only allow exec by wheel

---

nixos/common/sudo.nix

This makes it harder to replace sudo with sudo-rs

sudo: drop explicit sudo enable

---

nixos/common/openssh.nix

Forgejo is a fork of gitea and needs the same exception.

openssh: don't force authorizedKeysFiles if forgejo is enabled

---

nixos/mixins/cloud-init.nix

https://buildbot.nix-community.org/#/builders/11/builds/55/steps/2/logs/stdio
> trace: warning: The combination of `systemd.network.enable = true`, `networking.useDHCP = true` and `networking.useNetworkd = false` can cause both networkd and dhcpcd to manage the same interfaces. This can lead to loss of networking. It is recommended you choose only one of networkd (by also enabling `networking.useNetworkd`) or scripting (by disabling `systemd.network.enable`)

cloud-init: set network config to silence warning

---

.github/workflows/gh-pages.yml

Not on the nix community buildbot so the cache isn't available, I'd already removed the nixConfig but forgot this.

ci: remove `max-jobs = 0`

---

nixos/mixins/cloud-init.nix

cloud-init: don't flush the host's ssh keys

---

nixos/common/default.nix
nixos/server/default.nix

This feature was introduced in
https://github.com/NixOS/nixpkgs/pull/269551 and is mostly useful for
servers.
Saves around 80MiB of evaluation on x86_64 due to the extra i686 nixpkgs
instance.

no stub: <insert TLC song>

---

docs/github_actions_runner.md

Adds a small warning about ensuring you use bare metal or have kvm support if you intend running NixOS VM tests with the Github runner.

docs: advise bare metal or KVM support for Github Runner

---

nixos/mixins/telegraf.nix

This makes it a bit more flexible, e.g. if you need another prometheus input which uses tls client auth.

telegraf: use list for inputs.prometheus

---

nixos/hardware/hetzner-cloud/arm.nix

This timeout seems to be quite arbitrary, it is not specifically required for Hetzner ARM VMs.

hetzner-cloud/arm: remove boot.loader.timeout

---

nixos/common/nix.nix

Only set `nix.settings.experimental-features = ["repl-flake"]` when `config.nix.package.version` is older than version `2.22`. 
`repl-flake` was removed as an experimental feature and automatically enabled when using experimental feature: `flakes`

fix: Remove Nix experiemental-feature `repl-flake` after v2.22

---

nixos/common/default.nix

This implementation is meant to replace switch-to-configuration.pl with a rust version.
I tested it on my infra for now.

common: use new rust-based switch script

---

README.md
darwin/common/default.nix
darwin/common/flake.nix
darwin/common/nix.nix
darwin/common/openssh.nix
darwin/default.nix
darwin/desktop/default.nix
darwin/mixins/telegraf.nix
darwin/mixins/terminfo.nix
darwin/server/default.nix
docs/darwin/getting_started.md
docs/darwin/mixins.md
docs/darwin/type.md
docs/getting_started.md
docs/nixos/getting_started.md
docs/nixos/mixins.md
flake.nix
lib/exposeModules.nix
mkdocs.yml
nixos/default.nix

Now that this seems to be now also part of my own infastructure,
I kind of miss having srvos to share configuration.
Also there is some opportunity to share code with NixOS,
I decided to not do so as it would make contributing to this project harder
as not everyone has access to both Linux and MacOS at the same time.
I think it's acceptable to have a slight code drift, but allow to properly test
changes on both platforms in their own time.
I still need to update documentation here.

Darwin support

---

nixos/common/openssh.nix

This reverts commit b742b86532b2fba82e42acd106419d0d7419ed4f.
Bumped the inputs in https://github.com/nix-community/srvos/pull/450 for anyone following the srvos nixpkgs inputs.

Revert "common/openssh: apply workaround for CVE-2024-6387"

---

darwin/mixins/nix-experimental.nix

It breaks whoami in nix builds.

disable auto-allocate-uids on macOS

---

docs/nixos/hardware.md
nixos/hardware/hetzner-cloud/default.nix

This is useful to log in using the VNC console.
Tested, works as expected

hetzner-cloud: enable qemu-agent for password resets

---

nixos/common/serial.nix

It's actually more common for people to have graphical access i.e. most BMCs offer this by default. On the other hand its confusing if you don't get kernel logs on these outputs. That's why we now prefer graphical ttys over serial, but still enable console access on serial consoles

serial: change defaults to bring back kernel logs

---

darwin/common/openssh.nix

nix-darwin no longer allow to set this due to a security issue found in the implementation: https://github.com/LnL7/nix-darwin/commit/b833d4a32d965e6393a63b2c91b46eca2a5030d8
Fixes #456

darwin: drop removed services.openssh.authorizedKeysFiles option

---

nixos/server/default.nix

> programs.vim.defaultEditor will only work if programs.vim.enable is enabled, which will be enforced after the 24.11 release

fix vim warning

---

nixos/common/zfs.nix

In server scenario, disks are not getting shared, this is just not a thing. Don't force users to set this value.

feat(zfs): set default networking.hostId

---

dev/private.narHash
dev/private/flake.lock
dev/private/flake.nix

Unfollow nixos-stable since mkdocs-numtide depends on a plugin that is only available on nixos-unstable.

chore(flake): update mkdocs-numtide

---

docs/darwin/getting_started.md
docs/darwin/mixins.md
docs/darwin/type.md
docs/getting_started.md
docs/index.md
docs/nixos/getting_started.md
docs/nixos/hardware.md
docs/nixos/mixins.md
docs/nixos/role.md
docs/nixos/type.md
mkdocs.yml

Closes #476
Here's a first pass at linking to the modules. I thought about finding a way to automate this (eg. populating the links directly from the exposed flake modules) but couldn't find a clean solution.

feat(docs): Add links to module docs

---

nixos/mixins/cloud-init.nix
nixos/server/default.nix

Avoid clashes with the clan-core project.
1337 is in between mkDefault (1000) and mkOptionDefault (1500).

fix: set lower prio on networking.hostName

---

dev/private.narHash
dev/private/flake.lock
dev/private/flake.nix

One less nixpkgs input, everything is either on nixos-unstable-small or nixos-unstable.

dev/private/flake: add nixpkgs-dev input

---

nixos/hardware/hetzner-cloud/default.nix
nixos/hardware/vultr/vm.nix
nixos/server/default.nix

boot.loader.grub.device maps internally to boot.loader.grub.devices. Disko only sets boot.loader.grub.devices. By using the default priority we allow disko to override this value.
fixes https://github.com/nix-community/disko/issues/748

{hetzner-cloud, vultr}: don't conflict with disko

---

nixos/roles/nix-remote-builder.nix

Given the nix-daemon forking model, it can starve the remote builder of connections. Bump the limits.
See also https://github.com/nix-community/infra/pull/1417

fix(nix-remote-builder): allow more connections

---

nixos/mixins/systemd-boot.nix
nixos/server/default.nix

Avoid the full /boot partition issue by limiting the number of entries to add in said partition.
Since a boot entry (bzImage + initrd) is around 32MiB, this require the /boot partition to be at least 160MiB in size, 260MiB+ recommended (for the block sizes).
Ref: <https://www.ctrl.blog/entry/esp-size-guide.html>

feat(server): restrict boot entries to 5

---

nixos/server/default.nix

we disable emergency mode in systemd, but if systemd is enabled during boot we still end up in emergency mode eventually, this will fix that.

initrd.systemd: disable emergency mode

---

nixos/common/nix.nix

Channels are not reproducible and should be removed.
This change:
* removes the `nix-channel` binary
* sets an empty NIX_PATH
* stop adding the /root/.nix-channels file
This will lead scripts depending on channels to break, exposing their dependency on channels.

break(nix): disable nix channels

---

nixos/common/flake.nix

When `srvos.flake` is set, also set:
* NIX_PATH to the flake's nixpkgs input
* flake-registry to the flake's inputs
As suggested in #466 by @phaer

feat(srvos.flake): export the flake further

---

nixos/common/sudo.nix

I added custom rules to by sudo to allow a single user to restart a service.
Since srvos enables `security.sudo.execWheelOnly` by default, this breaks such use cases and it took me a while to debug it until I found out about this option.
Basically any sudo rule declared on anything else than `root` or `wheel` will not have any effect until this option is disabled again.
I now added an assertion to check for this scenario and crash with a nice error telling you to disable `execWheelOnly` if you declared any such rules

Add assertion for custom sudo rules

---

nixos/common/networking.nix

This was originally intended to disable scripted networking, but it's actually also an option that systemd-networkd respects. So we shouldn't have it.

no longer set networking.useDHCP to false

---

nixos/server/default.nix

There are hosts that cannot successfully perform a kexec and get stuck because no watchdog watches it. Timeout of `1m` is debatable.

Set watchdog for kexec to prevent hanging in case of missing firmware support

---

nixos/server/default.nix

If we have no man pages, we surely don't need the doc output or path.

Disable docs, too

---

darwin/common/nix.nix
darwin/desktop/default.nix

I think this is probably better suited for the desktop module like a similar nixos setting:
https://github.com/nix-community/srvos/blob/b7aa1d742955cfb96615d380f02049ec67f5abc0/nixos/desktop/default.nix#L12-L13

darwin: move nix.daemonIOLowPriority to desktop

---

darwin/common/openssh.nix

this is the equivalent of the setting that was removed in 9c9db0b387e7919ec13d6f4d762d4088c0c2d180

darwin: disable AuthorizedKeysFile

---

nixos/server/default.nix

Lower the watchdog interval to be Raspberry Pi compatible. See https://pimylifeup.com/raspberry-pi-watchdog/

decrease watchdog runtimeTime for Raspberry Pi compatibility

---

nixos/mixins/mdns.nix

`nixos/modules/tasks/network-interfaces-systemd.nix` only creates networkd networks if `useDHCP` is enabled. This is the case for the global setting, as well as the per-interface setting.
This commit only enables the multicast option globally if `useDHCP` is enabled globally. Additionally it enables MulticastDNS for each interface that has `useDHCP` enabled.

mdns: enable for all useDHCP interfaces

---

nixos/server/default.nix

Appearantly TCP BBR is not a good idea without doing any performance measurements: https://github.com/nix-community/srvos/pull/556
fq is actually incorrect. It should be `fq_codel` and systemd already applies this by default for us.

server/networking: unset tcp BBR and fq

---

.github/workflows/update-flake-lock.yml
dev/default.nix
dev/update-private-narhash

The issue with the current dev-flake setup is that `builtins.getFlake`
is not available in Nix, unless flakes are enabled. So this idea
of using flake-compat doesn't work.
Since the project is exporting modules, it doesn't matter. Replace the
top-level default.nix flake-compat with a simple attrset.

 chore: move update-private-narhash to script 

---

nixos/hardware/hetzner-online/default.nix

The standard configuration for the Hetzner online (robot) servers has
the standard NTP filtered.
```
sudo nix-shell -p nmap --command "nmap -sU -p 123 --script ntp-info 0.nixos.pool.ntp.org"
Starting Nmap 7.95 ( https://nmap.org ) at 2024-12-26 06:34 UTC
Nmap scan report for 0.nixos.pool.ntp.org (128.140.37.196)
Host is up (0.037s latency).
Other addresses for 0.nixos.pool.ntp.org (not scanned): 78.46.204.247 188.34.198.106 176.9.42.71
rDNS record for 128.140.37.196: ntp.heidenstedt.org
PORT    STATE         SERVICE
123/udp open|filtered ntp
Nmap done: 1 IP address (1 host up) scanned in 20.64 seconds
```
However, they provide their own NTP servers which are accessible in the
default configurations.
https://community.hetzner.com/tutorials/install-and-configure-ntp
so use these by default …

Add Hetzner time servers for NTP resolution

---

nixos/common/default.nix
nixos/common/detect-hostname-change.nix

NixOS is just too easy to deploy to the wrong host. Eg:
nixos-rebuild --flake .#wronghostname --target-host root@otherhost switch
It happened to me a few times, and when I started talking about it I
got the same feedback from other people.
After this change, the user now has to confirm with YES before the
switch can happen.
To disable, set
srvos.detect-hostname-change.enable = false;

feat: add hostname change detection

---

darwin/server/default.nix
nixos/common/default.nix
nixos/server/default.nix
shared/server.nix

Having a single option for the docs would be a bit simpler than needing to re-enable all the separate options.
I'll use this option to enable docs on the community builders.

server: add option to re-enable documentation

---

darwin/server/default.nix
nixos/server/default.nix

included by default since https://github.com/NixOS/nixpkgs/commit/280e9a5ca46e6e5e266871577436abc811d22262

nixos/server: remove root from trusted users, darwin/server: add @admin to trusted-users

---

darwin/common/update-diff.nix
nixos/common/update-diff.nix
shared/common/update-diff.nix

Using `preSwitchChecks` makes the diff work for switch-to-configuration `boot` as well as `switch`.

nixos/update-diff: activationScripts -> preSwitchChecks

---

nixos/common/detect-hostname-change.nix

Currently the detection fails if we're trying to do an installation from a NixOS system or installer, the only time I can see that check working is if someone was trying to run `nixos-install` directly from a non-NixOS Linux distro which would also require they have Nix installed which would be super uncommon

detect-hostname-change: improve installer detection

---

nixos/common/detect-hostname-change.nix

otherwise:
```
error: builder for '/nix/store/m03cxvyfj92nfvgnzxh97b8r0hchig94-pre-switch-checks.drv' failed with exit code 1;
last 7 log lines:
>
> In /nix/store/68a8lky97s5406nr49scpn9baj0vd59z-pre-switch-checks/bin/pre-switch-checks line 36:
> read reply
> ^--^ SC2162 (info): read without -r will mangle backslashes.
>
> For more information:
>   https://www.shellcheck.net/wiki/SC2162 -- read without -r will mangle backs...
For full logs, run 'nix log /nix/store/m03cxvyfj92nfvgnzxh97b8r0hchig94-pre-switch-checks.drv'.
```
i guess it's because of https://github.com/NixOS/nixpkgs/pull/375961

detect-hostname-change: make shellcheck happy

---

nixos/mixins/nginx.nix

Should not be enabled by default because important fixes are not getting merged. Trying to figure out that zstd is the culprit is tedious. Enabling the zstd module breaks SSI (used by jitsi-meet) and home-assistant.
See also:
- https://github.com/NixOS/nixpkgs/issues/359412
- https://github.com/NixOS/nixpkgs/pull/381037
- https://github.com/NixOS/nixpkgs/pull/381678

nginx: disable zstd

---

darwin/common/nix.nix
darwin/server/default.nix
nixos/common/nix.nix
nixos/server/default.nix

I was surprised to see that a sudoer in a desktop environment is not trusted by default. This sane setting applies in all environments, including desktops.
@moduon MT-9339

fix: sudoers are trusted in desktops too

---

darwin/common/nix.nix

`optimise.interval` is set but service isn't enabled.

darwin/nix: enable optimise by default

---

shared/common/update-diff.nix

so {option}`documentation.nixos.includeAllModules` doesn't complain

add description for update-diff.text

---

shared/common/update-diff.nix

```
copying path '/nix/store/c353hld7p5h24rfjl32zjhv3m2gh9rij-source' from 'https://nix-community.cachix.org'...
trace: evaluation warning: Attempt to evaluate package pkgs.nvd in option documentation; this is not supported and will eventually be an error. Use `mkPackageOption{,MD}` or `literalExpression` instead.
error:
------8<------8<-----
error: attribute 'nix' missing
at /nix/store/c353hld7p5h24rfjl32zjhv3m2gh9rij-source/shared/common/update-diff.nix:15:54:
14|       type = lib.types.singleLineStr;
15|       default = "${pkgs.nvd}/bin/nvd --nix-bin-dir=${config.nix.package}/bin diff";
|                                                      ^
16|       description = "diff command";
```
fix renders manual as such:
```man
srvos.update-diff.command
diff command
Type: (optionally …
```

update-diff: add defaultText for update-diff for docs

---

nixos/roles/prometheus/default-alerts.nix

Extract the host name from the instance label (e.g., "rauter.r:9273" -> "rauter") to enable proper grouping by host in Alertmanager routing rules.

prometheus: add host label to TelegrafDown alerts

---

shared/common/nix.nix

See details in
https://github.com/NixOS/nix/issues/3514#issuecomment-2313160224.

fix: allow failing ssh-ng substituters
