nix-community/srvos

flake.nix
profiles/common.nix
profiles/efi.nix

Moving us closer to trusted boot

use systemd-boot everywhere

---

profiles/common.nix

Stop using piles of bash scripts?

use systemd-networkd everywhere

---

README.md
default.nix
flake.nix
hardware/amazon/default.nix
hardware/hetzner-cloud/default.nix
mixins/cloud-init.nix

Introduce opinionated hardware configurations for cloud environments.

Add hardware

---

bors.toml
common/default.nix

srvos: disable initrd.systemd on systems with software raid

---

common/default.nix

initrd.systemd: fix condition to not enable when raids are used

---

default.nix
flake.nix
mixins/terminfo.nix
server.nix

graphical programs are prone to break and my hinder quick upgrades on
unstable channels: https://github.com/nix-community/infra/pull/379

make terminfo a mixin

---

.github/dependabot.yml
.github/workflows/update-flake-lock.yml

Automatically bump the flake and github action workflows

github and nix auto-updates

---

common/default.nix
common/flake.nix
common/well-known-hosts.nix
desktop/default.nix
hardware/amazon/default.nix
hardware/hetzner-cloud/default.nix
hardware/hetzner-online/amd.nix
hardware/hetzner-online/intel.nix
mixins/cloud-init.nix
mixins/nginx.nix
mixins/systemd-boot.nix
mixins/telegraf.nix
mixins/terminfo.nix
mixins/tracing.nix
modules/github-runners/service.nix
roles/github-actions-runner.nix
server.nix

See the second commit for a better description

Self references

---

common/default.nix
common/mdmonitor-fix.nix

See https://github.com/NixOS/nixpkgs/issues/72394#issuecomment-549110501

add fix for mdmonitor.service failure

---

docs/SUMMARY.md
docs/design.md

docs: explain the _file attribute

---

docs/SUMMARY.md
docs/default.nix
docs/nixos/roles.md
docs/nixos/roles/github_actions_runner.md

As this is not really obvious from the GitHub documentation explain how to register a new hosted runner github app

doc(github-runner): authentication

---

bors.toml
bors.toml.sh
checks/default.nix
flake.nix

A new trick to keep the bors.toml in sync between Garnix and the flake content.

flake: add bors TOML check

---

nixos/roles/nix-remote-builder.nix

from the description of the option:
Alias of users.users.

Don't use users.extraUsers alias

---

bors.toml
checks/default.nix

Start to get a bit more coverage

checks: add minimal NixOS test

---

nixos/roles/github-actions-runner.nix

GitHub Runner services are configured to makes the entire system read-only by default. Add a github-action-runner role option to allow specific paths to remain writable for the services.
To explicitely share files between runners in these paths, a shared group ID is also be added to the runners.

feat(github-runner): add extra read write paths option

---

nixos/mixins/cloud-init.nix

cloud-init: auto-enable used filesystems

---

flake.lock
nixos/hardware/vultr/vm.nix
nixos/modules/github-runners/default.nix

flake update

---

nixos/mixins/telegraf.nix

CI is expected to fail due to https://github.com/numtide/mkdocs-numtide/pull/3

telegraf: fix typo & deprecation warning, refactor exec checks

---

nixos/mixins/cloud-init.nix

cloud-init: add xfs

---

nixos/server/default.nix

This is useful to have around on hosts.

server: add git to systemPackages

---

dev/flake.lock
nixos/common/default.nix
nixos/common/mdmonitor-fix.nix
nixos/mixins/telegraf.nix

Let's make good examples for people to copy. This is considerably shorter and also puts the new thing first

simplify nixpkgs version checks

---

README.md

I use it in enough places now that I don't want to break.

README: mark it as stable

---

nixos/roles/nix-remote-builder.nix

see https://github.com/nix-community/infra/pull/838

nix-remote-builder: move to restrict option

---

nixos/common/upgrade-diff.nix

Forgot to include this in the previous PR, sorry.

upgrade-diff: add `nix-bin-dir` to nvd

---

README.md

Copied from the disko readme.
https://github.com/nix-community/disko/blob/master/README.md?plain=1#L135

README: add Numtide section

---

.github/workflows/gh-pages.yml
.github/workflows/nix.yml

Not using bors so these branches aren't needed.

ci: remove staging/trying branches

---

nixos/common/default.nix
nixos/hardware/hetzner-online/default.nix

fixes https://github.com/nix-community/srvos/pull/312

boot.initrd.systemd: also enable if initrd networkd is used

---

.gitignore
dev/checks.nix
dev/test-configurations.nix
flake.nix
nixos/modules/github-runners/default.nix

Since 23.11 it is no longer allowed to set nixpkgs.config when nixpkgs.pkgs is also set.

Don't set nixpkgs.config, it breaks some setups.

---

dev/private.narHash
dev/private/flake.lock
dev/private/flake.nix

Easier to add this separately to avoid merge conflicts.

dev/private/flake: add nix-darwin

---

dev/checks.nix
dev/test-configurations.nix
nixos/hardware/hetzner-online/default.nix
nixos/hardware/vultr/default.nix

This also fixes the Hetzner-online profile which wasn't tested before

fixup! vultr: disable srvos.boot.consoles

---

nixos/common/openssh.nix

openssh: move StreamLocalBindUnlink to settings

---

dev/test-configurations.nix
docs/nixos/hardware.md
nixos/default.nix
nixos/hardware/digitalocean/droplet.nix

untested but maybe @bbigras has already some thoughts on it.

add digitalocean

---

nixos/default.nix
nixos/desktop/default.nix
nixos/mixins/mdns.nix

It's quite cool if you can just ping machines by hostname.

enable multicast dns

---

nixos/hardware/amazon/default.nix

fixes https://github.com/nix-community/srvos/issues/414

amazon: drop redundant cloud-init.enable

---

nixos/server/default.nix

https://github.com/NixOS/nixpkgs/pull/326262 made defining sound.enable an eval error.

fix: drop removed sound.enable option

---

nixos/common/default.nix
nixos/common/mdmonitor-fix.nix

as this should be fixed at least as of 24.05 and later, see https://github.com/NixOS/nixpkgs/issues/72394

chore: drop mdmonitor-fix

---

darwin/common/flake.nix
nixos/common/flake.nix
nixos/common/serial.nix
nixos/modules/github-runners/default.nix
nixos/modules/github-runners/options.nix
nixos/roles/github-actions-runner.nix
nixos/roles/prometheus/default.nix

has been the default for a while

remove mddoc

---

nixos/server/default.nix

these are disable in the minimal profile

server: disable command-not-found, freedesktop xdg files

---

dev/test-configurations.nix
nixos/default.nix
nixos/mixins/latest-zfs-kernel.nix

This was remove from nixpkgs, but it's useful.

add latest zfs-kernel mixin

---

nixos/server/default.nix

I found this very useful in my testing of server configurations

Make sure the serial console is visible in qemu when testing the server

---

darwin/common/default.nix
darwin/common/update-diff.nix
nixos/common/default.nix
nixos/common/update-diff.nix
shared/common/update-diff.nix

also rename the files to match the option

add shared update-diff

---

nixos/mixins/mdns.nix

mdns: ensure MulticastDNS is set to a boolean value

---

nixos/roles/github-actions-runner.nix

queued build hook switched from buildGoPackage to buildGoModule

Update queued build hook

---

nixos/server/default.nix
shared/server.nix

git requires requires in graphics libraries dependencies etc.

depend on gitMinimal instead of git

---

nixos/mixins/nix-experimental.nix

https://github.com/NixOS/nixpkgs/pull/372878

nix-experimental: don't override `system-features`

---

darwin/common/default.nix
darwin/common/homebrew.nix

this has no effect if homebrew is not used.

add better homebrew defaults

---

darwin/server/default.nix

https://github.com/LnL7/nix-darwin/commit/9951b44d5bdebd062dab70701d7b21350cbbc6ab

darwin/server: includeUninstaller -> darwin-uninstaller

---

nixos/mixins/terminfo.nix

Nearly everybody at my work uses ghostty and though adding ghostty terminfo to the mixins might be a good idea.

added ghostty terminfo

---

nixos/mixins/terminfo.nix

This is hopefully as stable as ghostty by now.

mixins/terminfo: add kitty

---

nixos/server/default.nix

https://github.com/NixOS/nixpkgs/commit/1adf0f56ff95cae9db9fb198950b5c10ba52635b

nixos/server: systemd.watchdog -> systemd.settings.Manager
